#!/bin/bash
 
mkdir -p ai_files

rm -rf ai_files/*
 
declare -A file_counts
 
copy_file() {

    local file=$1

    local relative_path=${file#./}

    local base_name=$(basename "${file%.*}")
 
    if [[ -v "file_counts[$base_name]" ]]; then

        file_counts[$base_name]=$((file_counts[$base_name] + 1))

        dest_file="ai_files/${base_name}_${file_counts[$base_name]}.txt"

    else

        file_counts[$base_name]=1

        dest_file="ai_files/${base_name}.txt"

    fi
 
    # Add the path comment at the beginning of the new file

    {

        echo "// File: $relative_path"

        cat "$file"

    } > "$dest_file"

}
 
find ./app -type f | while read -r file; do

    copy_file "$file"

done
 
if [ -f "./prisma/schema.prisma" ]; then

    copy_file "./prisma/schema.prisma"

fi
 
gut add .
 